{% set version = "0.0.4" %}

package:
  name: roundrobin
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/r/roundrobin/roundrobin-{{ version }}.tar.gz
    sha256: 7e9d19a5bd6123d99993fb935fa86d25c88bb2096e493885f61737ed0f5e9abd

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  imports:
    - roundrobin
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/linnik/roundrobin
  summary: Collection of roundrobin utilities
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
